# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TsinghuaDaily Report

on:
  # 每天北京时间 10点整 (utc+8)自动运行
  schedule:
    - cron: "0 2 * * *"

jobs:
  submit_report:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python3 report.py
      env: # Or as an environment variable
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASS: ${{ secrets.USER_PASS }}
